In [8]:
import numpy as np


# Step 1 : Read The Data

In [18]:
path_file = "/content/makeSenseOfCensus.csv"

#Loading the data
data = np.genfromtxt(path_file, delimiter=",",skip_header=1)



print("\nData\n\n",data)



Data

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


**printing the type of data**

In [19]:
print(type(data))

<class 'numpy.ndarray'>


# Step 2: Append the Data

In [20]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]
df=np.concatenate((data,new_record))

In [25]:
df

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])


data[rows,columns]

: ---> all



# Step 3: Check if it's a young country or old country

**a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array**.

In [32]:
age=df[:,0]
print("Age",age)

Age [39. 50. 38. ... 40. 39. 50.]


**Find the max age and store it in a variable called 'max_age.'**

In [34]:
max_age=age.max()
print("Maximum age:",max_age)

Maximum age: 90.0


**Find the min age and store it in a variable called 'min_age'.**

In [24]:
min_age=age.min()
print(min_age)


17.0


**Find the mean of the age and store it in a variable called 'age_mean'.**

In [33]:
age_mean= age.mean()
print(age_mean)

38.06293706293706


**Find the standard deviation of the age and store it in a variable called 'age_std'**

In [31]:
age_std=np.std(age)
print(age_std)

13.341478176165857


# Step 4: Let's check the country's race distribution to identify the minorities

**Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)**

In [41]:

race_0= df[df[:,2]==0]
print(race_0)

[[34.  4.  0.  1.  0.  0. 45.  0.]
 [35. 10.  0.  0.  0.  0. 40.  0.]
 [60.  6.  0.  0.  0.  0. 10.  0.]
 [51.  9.  0.  1.  0.  0. 40.  0.]
 [25. 10.  0.  0.  0.  0. 20.  0.]
 [20.  9.  0.  1.  0.  0. 48.  0.]
 [23. 10.  0.  0.  0.  0. 25.  0.]
 [29.  9.  0.  1.  0.  0. 40.  0.]
 [27. 12.  0.  1.  0.  0. 40.  0.]
 [31. 12.  0.  0.  0.  0. 40.  0.]]


In [42]:
race_1=df[df[:,2]==1]


In [43]:
race_2=df[df[:,2]==2]

In [44]:
race_3=df[df[:,2]==3]
race_4=df[df[:,2]==4]

**Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively**

In [45]:
len_0=len(race_0)
len_1=len(race_1)
len_2=len(race_2)
len_3=len(race_3)
len_4=len(race_4)


**Find out which is the race with the minimum no. of citizens**

In [46]:
min_citizen=min(len_0,len_1,len_2,len_3,len_4)
print(min_citizen)

6


In [47]:
if min_citizen==len_0:
  print(" {} has minimum citizen= {} ".format("race_0",len_0))
elif min_citizen==len_1:
  print(" {} has minimum citizen= {} ".format("race_1",len_1))
elif min_citizen==len_2:
  print(" {} has minimum citizen= {}".format("race_2",len_2))
elif min_citizen==len_3:
  print(" {} has minimum citizen= {}".format("race_3",len_3))
else:
  print(" {} has minimum citizen= {}".format("race_4",len_4))



 race_3 has minimum citizen= 6


**Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )**



In [64]:
if min_citizen==len_0:
  minority_race=0
  
elif min_citizen==len_1:
  minority_race=1
elif min_citizen==len_2:
  minority_race=2
elif min_citizen==len_3:
  minority_race=3
else:
  minority_race=4

print("Minority Race= ",minority_race)

Minority Race=  3


# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

**Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)**


In [57]:
senior_citizens=df[df[:,0]>60]

**Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'**


In [54]:
working_hours_sum=sum(senior_citizens[:,6])
working_hours_sum

1917.0

**Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'**

In [70]:
senior_citizens_len=len(senior_citizens)

**Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.**


In [72]:
avg_workinghours=working_hours_sum/senior_citizens_len
print(avg_workinghours)

31.42622950819672


**Print 'avg_working_hours' and see if the govt. policy is followed.**

In [73]:
if avg_workinghours>25:
  print("Government policy is not followed")
else:
  print("Government policy is followed")

Government policy is not followed


# Step 6: Let's check that higher educated people have better pay in general.

**Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.**


In [55]:
high=df[df[:,1]>10]
low=df[df[:,1]<=10]

**Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.**


In [81]:
avg_pay_high=high[:,7].mean()
print("Average pay of higher educated citizen is : ",avg_pay_high)

Average pay of higher educated cittizen is :  0.42813455657492355


In [56]:
avg_pay_low=low[:,7].mean()
print("Average pay of less Educated Citizen is : ",avg_pay_low)

Average pay of less Educated Citizen is :  0.13649851632047477
